#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=00:30:00
#PBS -N 3Dfreesurfs
#PBS -V

rm -f finished
rm -rf surfaces

module load singularity 2> /dev/null

echo "converting aparc+aseg file"
echo $FREESURFER_LICENSE > license.txt
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.1 ./convertfiles.sh
#time singularity exec -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./convertfiles.sh"

echo "making surfaces"
export SINGULARITYENV_PYTHONNOUSERSITE=true
time singularity exec -e docker://brainlife/pythonvtk:1.1 ./main.py
#singularity exec -e docker://brainlife/docker-pythonvtk ./main.py

count=$(ls surfaces/* | wc -l)

if [ "$count" == 102 ] 
then
	echo 0 > finished
else
	echo "files missing"
	echo 1 > finished
	exit 1
fi
